"""add message

Revision ID: 4480c837ea9e
Revises: bfe24484c24
Create Date: 2016-07-23 23:22:15.227411

"""

# revision identifiers, used by Alembic.
revision = '4480c837ea9e'
down_revision = 'bfe24484c24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Unicode(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    ### end Alembic commands ###
