"""initial migration

Revision ID: bfe24484c24
Revises: None
Create Date: 2016-07-20 15:53:02.369856

"""

# revision identifiers, used by Alembic.
revision = 'bfe24484c24'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.Unicode(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('kindle_loc', sa.String(), nullable=True),
    sa.Column('qidian_login', sa.String(), nullable=True),
    sa.Column('qidian_password', sa.String(), nullable=True),
    sa.Column('hongxiu_login', sa.String(), nullable=True),
    sa.Column('hongxiu_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', 'users')
    op.drop_index('ix_users_email', 'users')
    op.drop_table('users')
    ### end Alembic commands ###
